// Initialize Zcash Bridge using raw transaction building
// Run with: node solana/init_bridge_raw.cjs

const {
    Connection,
    Keypair,
    PublicKey,
    LAMPORTS_PER_SOL,
    SystemProgram,
    Transaction,
    TransactionInstruction,
    SYSVAR_RENT_PUBKEY
} = require('@solana/web3.js');
const { TOKEN_PROGRAM_ID, createMint } = require('@solana/spl-token');
const fs = require('fs');
const path = require('path');
const borsh = require('borsh');

// Configuration
const RPC_URL = 'https://api.devnet.solana.com';
const PROGRAM_ID = new PublicKey('CofWCu36QKNwD7xy7TDtx6KBQJ2oN7aL5DszZwz89tvS');

// Anchor discriminator for "initialize" instruction
// Generated by: sha256("global:initialize")[0..8]
const INITIALIZE_DISCRIMINATOR = Buffer.from([175, 175, 109, 31, 13, 152, 155, 237]);

class BridgeConfig {
    constructor(props) {
        this.operator = props.operator;
        this.minDeposit = props.minDeposit;
        this.maxDeposit = props.maxDeposit;
        this.protocolFeeBps = props.protocolFeeBps;
    }
}

// Borsh schema for BridgeConfig
const BridgeConfigSchema = new Map([
    [BridgeConfig, {
        kind: 'struct',
        fields: [
            ['operator', [32]],
            ['minDeposit', 'u64'],
            ['maxDeposit', 'u64'],
            ['protocolFeeBps', 'u16'],
        ]
    }]
]);

function serializeBridgeConfig(config) {
    const configObj = new BridgeConfig({
        operator: config.operator.toBytes(),
        minDeposit: config.minDeposit,
        maxDeposit: config.maxDeposit,
        protocolFeeBps: config.protocolFeeBps,
    });
    return borsh.serialize(BridgeConfigSchema, configObj);
}

async function main() {
    console.log('================================================');
    console.log('  Initializing Zcash Bridge on Solana Devnet');
    console.log('================================================\n');

    // Load wallet keypair
    const keypairPath = path.join(__dirname, 'keypair.json');

    if (!fs.existsSync(keypairPath)) {
        console.error('❌ Keypair not found at:', keypairPath);
        process.exit(1);
    }

    const walletData = JSON.parse(fs.readFileSync(keypairPath, 'utf-8'));
    const walletKeypair = Keypair.fromSecretKey(Uint8Array.from(walletData));
    console.log('Wallet address:', walletKeypair.publicKey.toBase58());

    // Connect to Solana
    const connection = new Connection(RPC_URL, 'confirmed');

    // Check balance
    const balance = await connection.getBalance(walletKeypair.publicKey);
    console.log('Balance:', balance / LAMPORTS_PER_SOL, 'SOL\n');

    // Derive PDAs
    const [bridgeStatePda, bridgeBump] = PublicKey.findProgramAddressSync(
        [Buffer.from('bridge')],
        PROGRAM_ID
    );
    console.log('Bridge State PDA:', bridgeStatePda.toBase58());

    const [vaultPda, vaultBump] = PublicKey.findProgramAddressSync(
        [Buffer.from('vault')],
        PROGRAM_ID
    );
    console.log('Vault PDA:', vaultPda.toBase58());

    // Check if bridge is already initialized
    const bridgeAccount = await connection.getAccountInfo(bridgeStatePda);
    if (bridgeAccount && bridgeAccount.data.length > 0) {
        console.log('\n✅ Bridge already initialized!');
        console.log('Account data length:', bridgeAccount.data.length);
        console.log('Owner:', bridgeAccount.owner.toBase58());
        return;
    }

    console.log('\nBridge not initialized yet, proceeding...\n');

    // Create wrapped ZEC mint
    console.log('Creating wrapped ZEC mint...');
    let wrappedZecMint;
    try {
        wrappedZecMint = await createMint(
            connection,
            walletKeypair,
            walletKeypair.publicKey,
            walletKeypair.publicKey,
            8
        );
        console.log('Wrapped ZEC Mint:', wrappedZecMint.toBase58());
    } catch (e) {
        console.error('Failed to create mint:', e.message);
        // Use a placeholder mint for testing
        wrappedZecMint = Keypair.generate().publicKey;
        console.log('Using placeholder mint:', wrappedZecMint.toBase58());
    }

    // Build the config
    const config = {
        operator: walletKeypair.publicKey,
        minDeposit: BigInt(10000),
        maxDeposit: BigInt(1000 * LAMPORTS_PER_SOL),
        protocolFeeBps: 30,
    };

    // Build instruction data
    // Format: discriminator (8 bytes) + serialized config
    const configBuffer = Buffer.alloc(32 + 8 + 8 + 2); // operator + minDeposit + maxDeposit + feeBps
    config.operator.toBuffer().copy(configBuffer, 0);
    configBuffer.writeBigUInt64LE(config.minDeposit, 32);
    configBuffer.writeBigUInt64LE(config.maxDeposit, 40);
    configBuffer.writeUInt16LE(config.protocolFeeBps, 48);

    const instructionData = Buffer.concat([
        INITIALIZE_DISCRIMINATOR,
        configBuffer
    ]);

    console.log('Instruction data length:', instructionData.length);

    // Build the instruction
    const initializeIx = new TransactionInstruction({
        keys: [
            { pubkey: bridgeStatePda, isSigner: false, isWritable: true },
            { pubkey: walletKeypair.publicKey, isSigner: true, isWritable: true },
            { pubkey: wrappedZecMint, isSigner: false, isWritable: false },
            { pubkey: vaultPda, isSigner: false, isWritable: true },
            { pubkey: SystemProgram.programId, isSigner: false, isWritable: false },
            { pubkey: TOKEN_PROGRAM_ID, isSigner: false, isWritable: false },
            { pubkey: SYSVAR_RENT_PUBKEY, isSigner: false, isWritable: false },
        ],
        programId: PROGRAM_ID,
        data: instructionData,
    });

    // Build and send transaction
    console.log('\nSending initialize transaction...');

    const transaction = new Transaction().add(initializeIx);
    transaction.feePayer = walletKeypair.publicKey;

    const { blockhash } = await connection.getLatestBlockhash();
    transaction.recentBlockhash = blockhash;

    try {
        const signature = await connection.sendTransaction(transaction, [walletKeypair], {
            skipPreflight: false,
            preflightCommitment: 'confirmed',
        });

        console.log('Transaction sent:', signature);

        // Wait for confirmation
        const confirmation = await connection.confirmTransaction(signature, 'confirmed');

        if (confirmation.value.err) {
            console.error('Transaction failed:', confirmation.value.err);
            process.exit(1);
        }

        console.log('\n✅ Bridge initialized successfully!');
        console.log('Transaction:', signature);

        // Verify
        const newBridgeAccount = await connection.getAccountInfo(bridgeStatePda);
        if (newBridgeAccount) {
            console.log('\nBridge State Account:');
            console.log('  Size:', newBridgeAccount.data.length, 'bytes');
            console.log('  Owner:', newBridgeAccount.owner.toBase58());
        }

        console.log('\n================================================');
        console.log('  🎉 Success! Bridge is now initialized!');
        console.log('================================================');
        console.log('\nAdd to your .env:');
        console.log(`VITE_WRAPPED_ZEC_MINT=${wrappedZecMint.toBase58()}`);

    } catch (error) {
        console.error('\n❌ Transaction failed:', error.message);

        if (error.logs) {
            console.log('\nProgram logs:');
            error.logs.forEach(log => console.log('  ', log));
        }

        process.exit(1);
    }
}

main().catch(console.error);
