#!/bin/bash
set -e

echo "Building encrypted instructions..."

# Add Cargo to PATH
export PATH="$HOME/.cargo/bin:$PATH"

# Navigate to encrypted-ixs directory
cd "$(dirname "$0")/encrypted-ixs"

# Build encrypted instructions
echo "Compiling encrypted circuits..."
cargo build --release --target wasm32-unknown-unknown

# Create build directory if it doesn't exist
mkdir -p ../build

# Copy compiled .arcis files to build directory
# Note: The actual .arcis files are generated by arcis compiler
# For now, we'll create placeholder files
echo "Creating placeholder .arcis files..."
touch ../build/init_balance.arcis
touch ../build/deposit.arcis
touch ../build/execute_swap.arcis
touch ../build/add_order.arcis
touch ../build/match_orders.arcis
touch ../build/cancel_order.arcis

echo "Encrypted instructions build complete!"
