/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export type InEuint64Struct = {
  ctHash: BigNumberish;
  securityZone: BigNumberish;
  utype: BigNumberish;
  signature: BytesLike;
};

export type InEuint64StructOutput = [
  ctHash: bigint,
  securityZone: bigint,
  utype: bigint,
  signature: string
] & { ctHash: bigint; securityZone: bigint; utype: bigint; signature: string };

export interface FHPAYInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allowance"
      | "approve"
      | "balanceOf"
      | "balanceOfIsIndicator"
      | "confidentialBalanceOf"
      | "confidentialBurnFromController"
      | "confidentialMintFromController"
      | "confidentialTotalSupply"
      | "confidentialTransfer(address,(uint256,uint8,uint8,bytes))"
      | "confidentialTransfer(address,uint256)"
      | "confidentialTransferAndCall(address,uint256,bytes)"
      | "confidentialTransferAndCall(address,(uint256,uint8,uint8,bytes),bytes)"
      | "confidentialTransferFrom(address,address,(uint256,uint8,uint8,bytes))"
      | "confidentialTransferFrom(address,address,uint256)"
      | "confidentialTransferFromAndCall(address,address,uint256,bytes)"
      | "confidentialTransferFromAndCall(address,address,(uint256,uint8,uint8,bytes),bytes)"
      | "controller"
      | "decimals"
      | "devMintPlain"
      | "indicatorTick"
      | "isFherc20"
      | "isOperator"
      | "name"
      | "owner"
      | "renounceOwnership"
      | "resetIndicatedBalance"
      | "setController"
      | "setOperator"
      | "symbol"
      | "totalSupply"
      | "transfer"
      | "transferFrom"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ConfidentialTransfer"
      | "ControllerUpdated"
      | "OperatorSet"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allowance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOfIsIndicator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialBalanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialBurnFromController",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialMintFromController",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialTotalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialTransfer(address,(uint256,uint8,uint8,bytes))",
    values: [AddressLike, InEuint64Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialTransfer(address,uint256)",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialTransferAndCall(address,uint256,bytes)",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialTransferAndCall(address,(uint256,uint8,uint8,bytes),bytes)",
    values: [AddressLike, InEuint64Struct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialTransferFrom(address,address,(uint256,uint8,uint8,bytes))",
    values: [AddressLike, AddressLike, InEuint64Struct]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialTransferFrom(address,address,uint256)",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialTransferFromAndCall(address,address,uint256,bytes)",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialTransferFromAndCall(address,address,(uint256,uint8,uint8,bytes),bytes)",
    values: [AddressLike, AddressLike, InEuint64Struct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "controller",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "devMintPlain",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "indicatorTick",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "isFherc20", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isOperator",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resetIndicatedBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setController",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setOperator",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "balanceOfIsIndicator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialBalanceOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialBurnFromController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialMintFromController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialTotalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialTransfer(address,(uint256,uint8,uint8,bytes))",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialTransfer(address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialTransferAndCall(address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialTransferAndCall(address,(uint256,uint8,uint8,bytes),bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialTransferFrom(address,address,(uint256,uint8,uint8,bytes))",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialTransferFrom(address,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialTransferFromAndCall(address,address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialTransferFromAndCall(address,address,(uint256,uint8,uint8,bytes),bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "controller", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "devMintPlain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "indicatorTick",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isFherc20", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isOperator", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resetIndicatedBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ConfidentialTransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, value: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ControllerUpdatedEvent {
  export type InputTuple = [
    oldController: AddressLike,
    newController: AddressLike
  ];
  export type OutputTuple = [oldController: string, newController: string];
  export interface OutputObject {
    oldController: string;
    newController: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OperatorSetEvent {
  export type InputTuple = [
    holder: AddressLike,
    operator: AddressLike,
    until: BigNumberish
  ];
  export type OutputTuple = [holder: string, operator: string, until: bigint];
  export interface OutputObject {
    holder: string;
    operator: string;
    until: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FHPAY extends BaseContract {
  connect(runner?: ContractRunner | null): FHPAY;
  waitForDeployment(): Promise<this>;

  interface: FHPAYInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allowance: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  approve: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  balanceOf: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  balanceOfIsIndicator: TypedContractMethod<[], [boolean], "view">;

  confidentialBalanceOf: TypedContractMethod<
    [account: AddressLike],
    [bigint],
    "view"
  >;

  confidentialBurnFromController: TypedContractMethod<
    [from: AddressLike, value: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  confidentialMintFromController: TypedContractMethod<
    [to: AddressLike, value: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  confidentialTotalSupply: TypedContractMethod<[], [bigint], "view">;

  "confidentialTransfer(address,(uint256,uint8,uint8,bytes))": TypedContractMethod<
    [to: AddressLike, inValue: InEuint64Struct],
    [bigint],
    "nonpayable"
  >;

  "confidentialTransfer(address,uint256)": TypedContractMethod<
    [to: AddressLike, value: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  "confidentialTransferAndCall(address,uint256,bytes)": TypedContractMethod<
    [to: AddressLike, value: BigNumberish, data: BytesLike],
    [bigint],
    "nonpayable"
  >;

  "confidentialTransferAndCall(address,(uint256,uint8,uint8,bytes),bytes)": TypedContractMethod<
    [to: AddressLike, inValue: InEuint64Struct, data: BytesLike],
    [bigint],
    "nonpayable"
  >;

  "confidentialTransferFrom(address,address,(uint256,uint8,uint8,bytes))": TypedContractMethod<
    [from: AddressLike, to: AddressLike, inValue: InEuint64Struct],
    [bigint],
    "nonpayable"
  >;

  "confidentialTransferFrom(address,address,uint256)": TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  "confidentialTransferFromAndCall(address,address,uint256,bytes)": TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish, data: BytesLike],
    [bigint],
    "nonpayable"
  >;

  "confidentialTransferFromAndCall(address,address,(uint256,uint8,uint8,bytes),bytes)": TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      inValue: InEuint64Struct,
      data: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  controller: TypedContractMethod<[], [string], "view">;

  decimals: TypedContractMethod<[], [bigint], "view">;

  devMintPlain: TypedContractMethod<
    [to: AddressLike, value: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  indicatorTick: TypedContractMethod<[], [bigint], "view">;

  isFherc20: TypedContractMethod<[], [boolean], "view">;

  isOperator: TypedContractMethod<
    [holder: AddressLike, spender: AddressLike],
    [boolean],
    "view"
  >;

  name: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resetIndicatedBalance: TypedContractMethod<[], [void], "nonpayable">;

  setController: TypedContractMethod<
    [newController: AddressLike],
    [void],
    "nonpayable"
  >;

  setOperator: TypedContractMethod<
    [operator: AddressLike, until: BigNumberish],
    [void],
    "nonpayable"
  >;

  symbol: TypedContractMethod<[], [string], "view">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  transfer: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  transferFrom: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish],
    [boolean],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allowance"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "balanceOfIsIndicator"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "confidentialBalanceOf"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "confidentialBurnFromController"
  ): TypedContractMethod<
    [from: AddressLike, value: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialMintFromController"
  ): TypedContractMethod<
    [to: AddressLike, value: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialTotalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "confidentialTransfer(address,(uint256,uint8,uint8,bytes))"
  ): TypedContractMethod<
    [to: AddressLike, inValue: InEuint64Struct],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialTransfer(address,uint256)"
  ): TypedContractMethod<
    [to: AddressLike, value: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialTransferAndCall(address,uint256,bytes)"
  ): TypedContractMethod<
    [to: AddressLike, value: BigNumberish, data: BytesLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialTransferAndCall(address,(uint256,uint8,uint8,bytes),bytes)"
  ): TypedContractMethod<
    [to: AddressLike, inValue: InEuint64Struct, data: BytesLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialTransferFrom(address,address,(uint256,uint8,uint8,bytes))"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, inValue: InEuint64Struct],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialTransferFrom(address,address,uint256)"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialTransferFromAndCall(address,address,uint256,bytes)"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, value: BigNumberish, data: BytesLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialTransferFromAndCall(address,address,(uint256,uint8,uint8,bytes),bytes)"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      inValue: InEuint64Struct,
      data: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "controller"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "decimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "devMintPlain"
  ): TypedContractMethod<
    [to: AddressLike, value: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "indicatorTick"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isFherc20"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isOperator"
  ): TypedContractMethod<
    [holder: AddressLike, spender: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resetIndicatedBalance"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setController"
  ): TypedContractMethod<[newController: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setOperator"
  ): TypedContractMethod<
    [operator: AddressLike, until: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ConfidentialTransfer"
  ): TypedContractEvent<
    ConfidentialTransferEvent.InputTuple,
    ConfidentialTransferEvent.OutputTuple,
    ConfidentialTransferEvent.OutputObject
  >;
  getEvent(
    key: "ControllerUpdated"
  ): TypedContractEvent<
    ControllerUpdatedEvent.InputTuple,
    ControllerUpdatedEvent.OutputTuple,
    ControllerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OperatorSet"
  ): TypedContractEvent<
    OperatorSetEvent.InputTuple,
    OperatorSetEvent.OutputTuple,
    OperatorSetEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "ConfidentialTransfer(address,address,uint256)": TypedContractEvent<
      ConfidentialTransferEvent.InputTuple,
      ConfidentialTransferEvent.OutputTuple,
      ConfidentialTransferEvent.OutputObject
    >;
    ConfidentialTransfer: TypedContractEvent<
      ConfidentialTransferEvent.InputTuple,
      ConfidentialTransferEvent.OutputTuple,
      ConfidentialTransferEvent.OutputObject
    >;

    "ControllerUpdated(address,address)": TypedContractEvent<
      ControllerUpdatedEvent.InputTuple,
      ControllerUpdatedEvent.OutputTuple,
      ControllerUpdatedEvent.OutputObject
    >;
    ControllerUpdated: TypedContractEvent<
      ControllerUpdatedEvent.InputTuple,
      ControllerUpdatedEvent.OutputTuple,
      ControllerUpdatedEvent.OutputObject
    >;

    "OperatorSet(address,address,uint48)": TypedContractEvent<
      OperatorSetEvent.InputTuple,
      OperatorSetEvent.OutputTuple,
      OperatorSetEvent.OutputObject
    >;
    OperatorSet: TypedContractEvent<
      OperatorSetEvent.InputTuple,
      OperatorSetEvent.OutputTuple,
      OperatorSetEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
