import {ethers, network} from "hardhat";
import * as fs from "fs";
import * as path from "path";

type Mode = "ITS" | "GMP";

function getEnv(name: string): string {
  const v = process.env[name];
  if (!v) throw new Error(`Missing env var ${name}`);
  return v;
}

function getOptionalEnv(name: string): string | undefined {
  const v = process.env[name];
  return v && v.length > 0 ? v : undefined;
}

/**
 * Deploy AxelarPrivacyPool on the current network.
 *
 * Modes:
 * - GMP (recommended for Base Sepolia -> Polygon Sepolia): uses `aUSDC` via Axelar Gateway
 * - ITS: uses tokenId from an ITS token manager
 *
 * Required env:
 * - AXELAR_POOL_MODE = "GMP" | "ITS"
 * - AXELAR_POOL_DENOMINATION = human amount (e.g. "10")
 *
 * GMP env:
 * - AXELAR_GMP_SYMBOL = e.g. "aUSDC"
 *
 * ITS env (one of):
 * - AXELAR_ITS_TOKEN_MANAGER (contract w/ interchainTokenId())
 *   or
 * - AXELAR_ITS_TOKEN_ID (bytes32)
 *
 * Optional env:
 * - AXELAR_BRIDGE_ADDRESS (otherwise read from deployments/axelar-bridge.json for this network)
 */
async function main() {
  const networkName = network.name;
  const mode = (getEnv("AXELAR_POOL_MODE") as Mode).toUpperCase() as Mode;
  const denomHuman = getEnv("AXELAR_POOL_DENOMINATION");

  const bridgeAddressEnv = getOptionalEnv("AXELAR_BRIDGE_ADDRESS");
  const deploymentsPath = path.join(__dirname, "../../deployments/axelar-bridge.json");

  let bridgeAddress = bridgeAddressEnv;
  if (!bridgeAddress) {
    if (!fs.existsSync(deploymentsPath)) {
      throw new Error("Missing AXELAR_BRIDGE_ADDRESS and deployments/axelar-bridge.json not found");
    }
    const deployments = JSON.parse(fs.readFileSync(deploymentsPath, "utf8"));
    bridgeAddress = deployments?.[networkName]?.contractAddress;
  }
  if (!bridgeAddress) throw new Error(`No Axelar bridge address found for ${networkName}`);

  const [deployer] = await ethers.getSigners();
  const nativeBal = await ethers.provider.getBalance(deployer.address);
  console.log(`\nDeploying AxelarPrivacyPool on ${networkName}`);
  console.log(`Deployer: ${deployer.address}`);
  console.log(`Balance: ${ethers.formatEther(nativeBal)} ETH`);
  console.log(`Bridge: ${bridgeAddress}`);
  console.log(`Mode: ${mode}`);

  // Deploy MiMC hasher (bytecode generated by circomlibjs)
  const {mimcSpongecontract} = require("circomlibjs");
  const hasherBytecode = mimcSpongecontract.createCode("mimcsponge", 220);
  const HasherFactory = new ethers.ContractFactory(mimcSpongecontract.abi, hasherBytecode, deployer);
  console.log("\nDeploying MiMC hasher...");
  const hasher = await HasherFactory.deploy();
  await hasher.waitForDeployment();
  const hasherAddress = await hasher.getAddress();
  console.log(`Hasher: ${hasherAddress}`);

  console.log("\nDeploying Groth16 verifier...");
  const Groth16Verifier = await ethers.getContractFactory("Groth16Verifier");
  const verifier = await Groth16Verifier.deploy();
  await verifier.waitForDeployment();
  const verifierAddress = await verifier.getAddress();
  console.log(`Verifier: ${verifierAddress}`);

  const bridge = await ethers.getContractAt("AxelarStealthBridge", bridgeAddress, deployer);

  let tokenAddress: string;
  let itsTokenId = "0x" + "00".repeat(32);
  let gmpSymbol = "";

  if (mode === "ITS") {
    const tokenManager = getOptionalEnv("AXELAR_ITS_TOKEN_MANAGER");
    const tokenIdEnv = getOptionalEnv("AXELAR_ITS_TOKEN_ID");
    if (!tokenManager && !tokenIdEnv) {
      throw new Error("ITS mode requires AXELAR_ITS_TOKEN_MANAGER or AXELAR_ITS_TOKEN_ID");
    }

    if (tokenManager) {
      const tokenManagerAbi = ["function interchainTokenId() view returns (bytes32)"];
      const mgr = new ethers.Contract(tokenManager, tokenManagerAbi, deployer);
      itsTokenId = await mgr.interchainTokenId();
    } else if (tokenIdEnv) {
      itsTokenId = tokenIdEnv;
    }

    const itsAddress = await bridge.interchainTokenService();
    const itsAbi = ["function interchainTokenAddress(bytes32 tokenId) view returns (address)"];
    const its = new ethers.Contract(itsAddress, itsAbi, deployer);
    tokenAddress = await its.interchainTokenAddress(itsTokenId);
    if (tokenAddress === ethers.ZeroAddress) throw new Error("ITS tokenId not deployed on this chain");
    console.log(`ITS tokenId: ${itsTokenId}`);
    console.log(`ITS token:   ${tokenAddress}`);
  } else {
    gmpSymbol = getEnv("AXELAR_GMP_SYMBOL");
    const gateway = await bridge.gateway();
    const gwAbi = ["function tokenAddresses(string symbol) view returns (address)"];
    const gw = new ethers.Contract(gateway, gwAbi, deployer);
    tokenAddress = await gw.tokenAddresses(gmpSymbol);
    if (tokenAddress === ethers.ZeroAddress) throw new Error(`Gateway has no token for symbol ${gmpSymbol}`);
    console.log(`GMP symbol: ${gmpSymbol}`);
    console.log(`GMP token:  ${tokenAddress}`);
  }

  const erc20Abi = ["function decimals() view returns (uint8)"];
  const token = new ethers.Contract(tokenAddress, erc20Abi, deployer);
  const decimals: number = await token.decimals();
  const denomination = ethers.parseUnits(denomHuman, decimals);
  console.log(`Denomination: ${denomHuman} (${denomination.toString()} wei, decimals=${decimals})`);

  console.log("\nDeploying AxelarPrivacyPool...");
  const AxelarPrivacyPool = await ethers.getContractFactory("AxelarPrivacyPool");
  const pool = await AxelarPrivacyPool.deploy(
    tokenAddress,
    denomination,
    hasherAddress,
    bridgeAddress,
    itsTokenId,
    gmpSymbol,
    verifierAddress
  );
  await pool.waitForDeployment();
  const poolAddress = await pool.getAddress();
  console.log(`Pool: ${poolAddress}`);

  const outPath = path.join(__dirname, "../../deployments/axelar-pool.json");
  let out: any = {};
  if (fs.existsSync(outPath)) out = JSON.parse(fs.readFileSync(outPath, "utf8"));
  out[networkName] = {
    network: networkName,
    chainId: Number((await ethers.provider.getNetwork()).chainId),
    pool: poolAddress,
    hasher: hasherAddress,
    verifier: verifierAddress,
    bridge: bridgeAddress,
    mode,
    denomination: denomination.toString(),
    token: tokenAddress,
    itsTokenId,
    gmpSymbol,
    timestamp: new Date().toISOString(),
  };
  fs.mkdirSync(path.dirname(outPath), {recursive: true});
  fs.writeFileSync(outPath, JSON.stringify(out, null, 2));
  console.log(`\nSaved: ${outPath}`);

  console.log("\nNext:");
  console.log(`- Deposit: bunx hardhat run scripts/axelar-pool/poolDeposit.ts --network ${networkName}`);
  console.log(`- Withdraw: bunx hardhat run scripts/axelar-pool/poolWithdrawAndBridge.ts --network ${networkName}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});

